# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 13:48
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_add_userena_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_address', models.EmailField(choices=[('noreply@fudulbank.com', 'noreply@fudulbank.com'), ('support@fudulbank.com', 'support@fudulbank.com')], max_length=254)),
                ('subject', models.CharField(max_length=140)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='')),
                ('target', models.CharField(choices=[('INSTITUTIONS', 'Per institutions'), ('COLLEGES', 'Per colleges'), ('ALL', 'All confirmed users')], default='ALL', max_length=20)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('colleges', models.ManyToManyField(blank=True, to='accounts.College')),
                ('institutions', models.ManyToManyField(blank=True, to='accounts.Institution')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
