# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-04 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('PROCESSING', 'Processing')], default='PENDING', max_length=20),
        ),
    ]
