# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-03 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_not_null_nickname'),
        ('mailer', '0002_status_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='batches',
            field=models.ManyToManyField(blank=True, to='accounts.Batch'),
        ),
        migrations.AlterField(
            model_name='message',
            name='target',
            field=models.CharField(choices=[('INSTITUTIONS', 'Per institutions'), ('COLLEGES', 'Per colleges'), ('BATCHES', 'Per batch'), ('ALL', 'All confirmed users')], default='ALL', max_length=20),
        ),
    ]
