# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-13 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0003_support_batches'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='colleges',
            new_name='groups',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='batches',
            new_name='levels',
        ),
    ]
