# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-03 03:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0004_group_level_relationships'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='submitter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
