# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 18:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code_name', models.CharField(max_length=200)),
                ('access', models.CharField(choices=[('editors', 'Editors'), ('collectors', 'Collectors')], default='', max_length=10)),
                ('members', models.ManyToManyField(blank=True, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
