# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_add_categories_and_exams'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='categories',
            field=models.ManyToManyField(related_name='privileged_teams', to='exams.Category'),
        ),
    ]
