# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='can_publish',
        ),
        migrations.RemoveField(
            model_name='team',
            name='city',
        ),
        migrations.RemoveField(
            model_name='team',
            name='college',
        ),
        migrations.RemoveField(
            model_name='team',
            name='coordinator',
        ),
        migrations.RemoveField(
            model_name='team',
            name='gender',
        ),
        migrations.AddField(
            model_name='team',
            name='access',
            field=models.CharField(choices=[('editors', 'Editors'), ('collectors', 'Collectors')], default='', max_length=10),
        ),
    ]
