# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 22:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_editors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='access',
        ),
    ]
