# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0071_rule_is_disabled'),
        ('teams', '0004_remove_team_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='exams',
            field=models.ManyToManyField(related_name='privileged_teams', to='exams.Exam'),
        ),
    ]
