# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoreMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='core_members')),
                ('background', models.ImageField(blank=True, upload_to='core_members')),
                ('role', models.CharField(max_length=200)),
                ('twitter', models.URLField(blank=True)),
            ],
        ),
    ]
