# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-25 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('language', models.CharField(choices=[('ar', 'العربية'), ('en', 'الإنجليزية')], default='en', max_length=2)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
