# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-25 08:38
from __future__ import unicode_literals

from django.db import migrations

def add_donation_messages(apps, schema_editor):
    DonationMessage = apps.get_model('core', 'DonationMessage')
    DonationMessage.objects.create(text='Fudul is bigger and more useful than ever and we need you to keep it going.')

def delete_donation_messages(apps, schema_editor):
    DonationMessage = apps.get_model('core', 'DonationMessage')
    DonationMessage.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_donationmessage'),
    ]

    operations = [
        migrations.RunPython(add_donation_messages,
                             reverse_code=delete_donation_messages)
    ]
