# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 06:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170609_0259'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blocks', '0002_update_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='url')),
                ('name', models.CharField(max_length=100)),
                ('college_limit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.College')),
                ('parent_category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='blocks.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('batches_allowed_to_take', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Batch')),
                ('submitter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blocks.Year')),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='answer_explanation')),
                ('is_approved', models.BooleanField(default=False)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('approval_date', models.DateField(blank=True, null=True, verbose_name='Approval_date')),
                ('is_deleted', models.BooleanField(default=False)),
                ('submitter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.College')),
            ],
        ),
        migrations.RemoveField(
            model_name='block',
            name='submitter',
        ),
        migrations.RemoveField(
            model_name='block',
            name='year',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='type',
            new_name='exam_type',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='question',
            name='explanation',
        ),
        migrations.RemoveField(
            model_name='question',
            name='submission_date',
        ),
        migrations.RemoveField(
            model_name='question',
            name='submitter',
        ),
        migrations.RemoveField(
            model_name='question',
            name='text',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='block',
        ),
        migrations.AddField(
            model_name='choice',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='figure',
            field=models.FileField(blank=True, null=True, upload_to='exams/question_image'),
        ),
        migrations.DeleteModel(
            name='Block',
        ),
        migrations.AddField(
            model_name='choice',
            name='revision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blocks.Revision'),
        ),
        migrations.AddField(
            model_name='question',
            name='source',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='blocks.Source'),
        ),
        migrations.AddField(
            model_name='subject',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blocks.Exam'),
        ),
    ]
