# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 02:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170609_0259'),
        ('blocks', '0003_update_models_structure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='year',
        ),
        migrations.AddField(
            model_name='exam',
            name='parent_category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='blocks.Category'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='category',
            name='college_limit',
        ),
        migrations.AddField(
            model_name='category',
            name='college_limit',
            field=models.ManyToManyField(blank=True, to='accounts.College'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='batches_allowed_to_take',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Batch'),
        ),
    ]
