# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0004_link_exam_to_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_complete',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='revision',
            name='question',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blocks.Question'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='question',
            name='source',
        ),
        migrations.AddField(
            model_name='question',
            name='source',
            field=models.ManyToManyField(blank=True, default='', to='blocks.Source'),
        ),
    ]
