# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 19:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0005_modify_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='parent_category',
            new_name='category',
        ),
    ]
