# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0006_auto_20170612_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='subject',
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ManyToManyField(to='blocks.Subject'),
        ),
    ]
