# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0007_subject_M2M_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_complete',
        ),
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('C', 'complete'), ('S', 'spelling error'), ('A', 'incomplete answers'), ('Q', 'incomplete question')], default='', max_length=1),
        ),
    ]
