# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 00:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0008_add_status_to_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='is_deleted',
        ),
    ]
