# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 01:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0009_remove_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='year',
            name='college',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='submitter',
        ),
        migrations.RemoveField(
            model_name='source',
            name='college',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='submitter',
        ),
        migrations.AddField(
            model_name='source',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blocks.Exam'),
        ),
        migrations.AddField(
            model_name='source',
            name='submission_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='figure',
            field=models.ImageField(blank=True, null=True, upload_to='exams/question_image'),
        ),
        migrations.AlterField(
            model_name='revision',
            name='approval_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='revision',
            name='explanation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
