# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0010_auto_20170613_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='source',
            field=models.ManyToManyField(blank=True, to='blocks.Source'),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.ManyToManyField(blank=True, to='blocks.Subject'),
        ),
    ]
