# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 08:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0011_auto_20170613_0806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='source',
            new_name='sources',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='subject',
            new_name='subjects',
        ),
    ]
