# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 04:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='الاسم')),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('mobile_number', models.CharField(max_length=14)),
                ('alternative_email', models.EmailField(blank=True, max_length=254)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True, null=True)),
                ('college', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.College')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مستخدمـ/ـة')),
            ],
        ),
        migrations.AddField(
            model_name='college',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Institution', verbose_name='المؤسسة'),
        ),
    ]
