# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 02:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='الاسم')),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ar_first_name', models.CharField(max_length=30, verbose_name='الاسم الأول')),
                ('ar_middle_name', models.CharField(max_length=30, verbose_name='الاسم الأوسط')),
                ('ar_last_name', models.CharField(max_length=30, verbose_name='الاسم الأخير')),
                ('en_first_name', models.CharField(max_length=30, verbose_name='الاسم الأول')),
                ('en_middle_name', models.CharField(max_length=30, verbose_name='الاسم الأوسط')),
                ('en_last_name', models.CharField(max_length=30, verbose_name='الاسم الأخير')),
                ('mobile_number', models.CharField(max_length=14, verbose_name='رقم الجوال')),
                ('submission_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('modification_date', models.DateTimeField(auto_now=True, null=True, verbose_name='تاريخ التعديل')),
                ('college', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.College', verbose_name='الكلية')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مستخدمـ/ـة')),
            ],
        ),
        migrations.AddField(
            model_name='college',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Institution', verbose_name='المؤسسة'),
        ),
    ]
