# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 01:33
from __future__ import unicode_literals

from django.db import migrations, models
import easy_thumbnails.fields
import userena.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('view_profile', 'Can view profile'),)},
        ),
        migrations.AddField(
            model_name='profile',
            name='mugshot',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, help_text='A personal image displayed in your profile.', upload_to=userena.models.upload_to_mugshot, verbose_name='mugshot'),
        ),
        migrations.AddField(
            model_name='profile',
            name='privacy',
            field=models.CharField(choices=[('open', 'Open'), ('registered', 'Registered'), ('closed', 'Closed')], default='registered', help_text='Designates who can view your profile.', max_length=15, verbose_name='privacy'),
        ),
    ]
