# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-15 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_userena_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='complete_number',
            field=models.PositiveIntegerField(null=True, blank=True),
        ),
    ]
