# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-15 06:25
from __future__ import unicode_literals

from django.db import migrations

def fill_batch_counts(apps, schema_editor):
    Batch = apps.get_model('accounts', 'Batch')
    
    batch_counts = {'Batch 11': 179,
                    'Batch 12': 288,
                    'Batch 13': 328,
                    'Batch 14': 292}

    for batch_name in batch_counts:
        count = batch_counts[batch_name]
        try:
            batch = Batch.objects.get(name=batch_name,
                                      college__name="College of Medicine",
                                      college__institution__name="KSAU-HS")
        except Batch.DoesNotExist:
            continue
        else:
            batch.complete_number = count
            batch.save()

def empty_batch_counts(apps, schema_editor):
    Batch = apps.get_model('accounts', 'Batch')
    Batch.objects.update(complete_number=None)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_batch_complete_number'),
    ]

    operations = [
        migrations.RunPython(fill_batch_counts,
                             reverse_code=empty_batch_counts)
    ]
