# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-16 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_fill_batch_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='display_full_name',
            field=models.CharField(choices=[('Y', 'Display my full name'), ('N', 'Only display nickname')], default='N', max_length=1),
        ),
    ]
