# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-25 18:20
from __future__ import unicode_literals

import accounts.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_fields_for_personal_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='profile',
            managers=[
                ('objects', accounts.managers.ProfileManger()),
            ],
        ),
    ]
