# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-17 08:43
from __future__ import unicode_literals

from django.contrib.contenttypes.management import create_contenttypes
from django.db import migrations

def add_primary_interests(apps, schema_editor):
    Category = apps.get_model('exams', 'Category')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Exam = apps.get_model('exams', 'Exam')
    PrimaryInterest = apps.get_model('accounts', 'PrimaryInterest')
    Profile = apps.get_model('accounts', 'Profile')

    exam_app = apps.app_configs['exams']
    exam_app.models_module = exam_app.models_module or True

    create_contenttypes(exam_app, apps=apps)

    exam_content_type = ContentType.objects.get(app_label='exams', model='exam')
    category_content_type = ContentType.objects.get(app_label='exams', model='category')

    if Exam.objects.filter(name="SMLE").exists():
        smle, was_created = PrimaryInterest.objects.get_or_create(name="SMLE",
                                                                  object_id=Exam.objects.get(name="SMLE").pk,
                                                                  content_type=exam_content_type)
        Profile.objects.filter(main_interest="SMLE").update(primary_interest=smle)
    if Exam.objects.filter(name="SNLE").exists():
        snle, was_created = PrimaryInterest.objects.get_or_create(name="SNLE",
                                                              object_id=Exam.objects.get(name="SNLE").pk,
                                                              content_type=exam_content_type)
        Profile.objects.filter(main_interest="SNLE").update(primary_interest=snle)

    if Exam.objects.filter(name="Pediatrics Saudi Board").exists():
        residencies, was_created = PrimaryInterest.objects.get_or_create(name="Residency programs")
        PrimaryInterest.objects.get_or_create(name="Pediatric Saudi Board",
                                              parent=residencies,
                                              object_id=Exam.objects.get(name="Pediatrics Saudi Board").pk,
                                              content_type=exam_content_type)

    colleges, was_created = PrimaryInterest.objects.get_or_create(name="College programs")
    ksau_hs, was_created  = PrimaryInterest.objects.get_or_create(name="King Saud bin Abdulaziz University for Health Sciences",
                                                                  parent=colleges,
                                                                  object_id=Category.objects.get(name="KSAU-HS").pk,
                                                                  content_type=category_content_type)

    Profile.objects.filter(main_interest="COLLEGES").update(primary_interest=ksau_hs)

def remove_primary_interests(apps, schema_editor):
    PrimaryInterest = apps.get_model('accounts', 'PrimaryInterest')
    PrimaryInterest.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('accounts', '0012_improve_primary_interests'),
    ]

    operations = [
        migrations.RunPython(add_primary_interests,
                             remove_primary_interests)
    ]
