# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-17 09:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_add_primary_interests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='main_interest',
        ),
    ]
