# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-24 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0082_session_theme'),
        ('accounts', '0014_remove_profile_main_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='session_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.SessionTheme'),
        ),
    ]
