# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-11 19:50
from __future__ import unicode_literals

from django.db import migrations

def fill_is_editor(apps, schema_editor):
    Profile = apps.get_model('accounts', 'Profile')
    Profile.objects.filter(user__team_memberships__isnull=False).update(is_editor=True)

def empty_is_editor(apps, schema_editor):
    Profile = apps.get_model('accounts', 'Profile')
    Profile.objects.update(is_editor=False)

class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('accounts', '0016_profile_is_editor'),
    ]

    operations = [
        migrations.RunPython(fill_is_editor,
                             reverse_code=empty_is_editor)
    ]
