# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-13 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0003_support_batches'),
        ('accounts', '0017_fill_is_editor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='College',
            new_name='Group',
        ),
        migrations.RenameModel(
            old_name='Batch',
            new_name='Level',
        ),
    ]
