# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-13 20:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_group_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='college',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='college',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='batch',
            new_name='level',
        ),
    ]
