# Generated by Django 2.2.5 on 2019-10-24 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_fill_on_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_examiner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='primary_interest',
            field=models.ForeignKey(blank=True, limit_choices_to={'children__isnull': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.PrimaryInterest'),
        ),
    ]
