# Generated by Django 2.2.12 on 2020-05-15 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_support_examiners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primaryinterest',
            name='category',
        ),
        migrations.RemoveField(
            model_name='primaryinterest',
            name='exam',
        ),
    ]
