# Generated by Django 2.2.12 on 2020-05-15 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_primary_interest_rm_exam_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primaryinterest',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounts.PrimaryInterest'),
        ),
    ]
