# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_add_categories_and_exams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('COMPLETE', 'Complete and valid question'), ('SPELLING', 'Improper spelling'), ('INCOMPLETE_ANSWERS', 'Incomplete answers'), ('INCOMPLETE_QUESTION', 'Incomplete question')], default='', max_length=30),
        ),
    ]
