# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_update_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='is_answer',
            field=models.BooleanField(default=False, verbose_name='Right answer?'),
        ),
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('COMPLETE', 'Complete and valid question'), ('WRITING_ERROR', 'Writing errors'), ('INCOMPLETE_ANSWERS', 'Incomplete answers'), ('INCOMPLETE_QUESTION', 'Incomplete question'), ('UNSOLVED', 'Unsolved question')], default='', max_length=30),
        ),
    ]
