# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 20:35
from __future__ import unicode_literals

from django.db import migrations

def fill_is_first(apps, schema_editor):
    Question = apps.get_model('exams', 'Question')
    for question in Question.objects.iterator():
        revision = question.revision_set.order_by("submission_date").first()
        revision.is_first = True
        revision.save()

def empty_is_first(apps, schema_editor):
    Revision = apps.get_model('exams', 'Revision')
    Revision.objects.update(is_first=False)

class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_is_first'),
    ]

    operations = [
        migrations.RunPython(fill_is_first,
                             reverse_code=empty_is_first)
    ]
