# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 02:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_move_images_to_revision'),
        ('exams', '0006_fill_is_first'),
    ]

    operations = [
    ]
