# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 21:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_fill_is_first'),
        ('exams', '0005_add_OSPE_to_types'),
    ]

    operations = [
    ]
