# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_merge_20170617_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='is_last',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='exam_type',
            field=models.CharField(choices=[('FINAL', 'Final'), ('MIDTERM', 'Midterm'), ('FORMATIVE', 'Formative'), ('OSPE', 'OSPE')], max_length=15),
        ),
    ]
