# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 04:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_fill_is_last'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='parent_question',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='exams.Question'),
        ),
        migrations.AddField(
            model_name='revision',
            name='status',
            field=models.CharField(choices=[('COMPLETE', 'Complete and valid question'), ('WRITING_ERROR', 'Writing errors'), ('INCOMPLETE_ANSWERS', 'Incomplete answers'), ('INCOMPLETE_QUESTION', 'Incomplete question'), ('UNSOLVED', 'Unsolved question')], default='', max_length=30),
            preserve_default=False,
        ),
    ]
