# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0012_add_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='exam_type',
            field=models.CharField(blank=True, choices=[('FINAL', 'Final'), ('MIDTERM', 'Midterm'), ('FORMATIVE', 'Formative'), ('OSPE', 'OSPE')], max_length=15),
        ),
        migrations.AlterField(
            model_name='question',
            name='statuses',
            field=models.ManyToManyField(to='exams.Status'),
        ),
        migrations.AlterField(
            model_name='question',
            name='subjects',
            field=models.ManyToManyField(to='exams.Subject'),
        ),
    ]
