# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0013_change_blanks'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='statuses',
            field=models.ManyToManyField(to='exams.Status'),
        ),
    ]
