# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 17:15
from __future__ import unicode_literals

from django.db import migrations

def add_statuses(apps, schema_editor):
    Status = apps.get_model('exams', 'Status')
    Revision = apps.get_model('exams', 'Revision')

    for status in Status.objects.all():
        status_questions = status.question_set.all()
        question_revisions = Revision.objects.filter(question__in=status_questions)
        status.revision_set.add(*question_revisions)

def remove_statuses(apps, schema_editor):
    Status = apps.get_model('exams', 'Status')
    Question = apps.get_model('exams', 'Question')

    for status in Status.objects.all():
        status_revisions = status.revision_set.all()
        revision_questions = Question.objects.filter(revision__in=status_revisions)
        status.question_set.add(*revision_questions)

class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0014_revision_statuses'),
    ]

    operations = [
        migrations.RunPython(add_statuses,
                             reverse_code=remove_statuses)

    ]
