# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 18:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0015_move_statuses_to_revision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='status',
        ),
        migrations.RemoveField(
            model_name='revision',
            name='status',
        ),
    ]
