# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 15:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0016_remove_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ansewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_marked', models.BooleanField(default=False, verbose_name='is marked ?')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explained', models.BooleanField(default=False, verbose_name='show explaination?')),
                ('solved', models.BooleanField(default=False, verbose_name='solved questions')),
                ('number_of_questions', models.IntegerField(default=0)),
                ('session_type', models.CharField(blank=True, choices=[('', '')], max_length=15)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Exam')),
                ('questions', models.ManyToManyField(to='exams.Question')),
                ('sources', models.ManyToManyField(blank=True, to='exams.Source')),
                ('subjects', models.ManyToManyField(to='exams.Subject')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ansewer',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Session'),
        ),
        migrations.AddField(
            model_name='ansewer',
            name='submitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
