# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 10:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0017_add_exams'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code_name', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Category')),
            ],
        ),
        migrations.AlterField(
            model_name='session',
            name='explained',
            field=models.BooleanField(default=False, verbose_name='Show explaination?'),
        ),
        migrations.AlterField(
            model_name='session',
            name='number_of_questions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.CharField(blank=True, choices=[('FINAL', 'Final'), ('MIDTERM', 'Midterm'), ('FORMATIVE', 'Formative'), ('OSPE', 'OSPE')], max_length=15),
        ),
        migrations.AlterField(
            model_name='session',
            name='solved',
            field=models.BooleanField(default=False, verbose_name='Show solved questions?'),
        ),
        migrations.AddField(
            model_name='question',
            name='exam_types',
            field=models.ManyToManyField(to='exams.ExamType'),
        ),
        migrations.AddField(
            model_name='session',
            name='exam_types',
            field=models.ManyToManyField(to='exams.ExamType'),
        ),
    ]
