# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0019_fill_exam_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='parent_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='exams.Source'),
        ),
    ]
