# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 11:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0020_source_parent_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='exam_type',
        ),
        migrations.RemoveField(
            model_name='session',
            name='session_type',
        ),
    ]
