# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 22:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0021_exam_type_clean_up'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_marked', models.BooleanField(default=False, verbose_name='is marked ?')),
                ('choice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.Choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Question')),
            ],
        ),
        migrations.RemoveField(
            model_name='ansewer',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='ansewer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='ansewer',
            name='session',
        ),
        migrations.RemoveField(
            model_name='ansewer',
            name='submitter',
        ),
        migrations.RemoveField(
            model_name='session',
            name='explained',
        ),
        migrations.AddField(
            model_name='session',
            name='is_marked',
            field=models.ManyToManyField(related_name='marked', to='exams.Question'),
        ),
        migrations.AddField(
            model_name='session',
            name='right_answers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Ansewer',
        ),
        migrations.AddField(
            model_name='answer',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Session'),
        ),
    ]
