# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0022_remove_explained_from_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='incoorect',
            field=models.BooleanField(default=False, verbose_name='Incoorect'),
        ),
        migrations.AddField(
            model_name='session',
            name='marked',
            field=models.BooleanField(default=False, verbose_name='Marked'),
        ),
        migrations.AddField(
            model_name='session',
            name='unsloved',
            field=models.BooleanField(default=False, verbose_name='Unsolved'),
        ),
        migrations.AlterField(
            model_name='session',
            name='solved',
            field=models.BooleanField(default=False, verbose_name='Solved Questions'),
        ),
    ]
