# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0023_more_question_filtering'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='question_filter',
            field=models.CharField(choices=[('U', 'Unused'), ('I', 'Incorrect'), ('A', 'All'), ('C', 'Custom')], default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='incoorect',
            field=models.BooleanField(default=False, verbose_name='Incorrect'),
        ),
    ]
