# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0024_add_question_filter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='incoorect',
        ),
        migrations.RemoveField(
            model_name='session',
            name='is_marked',
        ),
        migrations.RemoveField(
            model_name='session',
            name='unsloved',
        ),
        migrations.RemoveField(
            model_name='session',
            name='marked',
        ),
        migrations.AddField(
            model_name='session',
            name='marked',
            field=models.ManyToManyField(related_name='marked', to='exams.Question'),
        ),
        migrations.AlterField(
            model_name='session',
            name='question_filter',
            field=models.CharField(choices=[('U', 'Unused'), ('I', 'Incorrect'), ('A', 'All'), ('C', 'Custom'), ('R', 'Random')], default=None, max_length=1),
        ),
    ]
