# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0026_further_session_cleanup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='is_solved',
        ),
        migrations.AddField(
            model_name='session',
            name='session_mode',
            field=models.CharField(choices=[('EXPLAINED', 'Explained'), ('UNEXPLAINED', 'Unexplained'), ('SOLVED', 'Solved')], default="", max_length=20),
        ),
    ]
