# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0027_session_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='parent_question',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_question', to='exams.Question'),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_mode',
            field=models.CharField(choices=[('EXPLAINED', 'Explained'), ('UNEXPLAINED', 'Unexplained'), ('SOLVED', 'Solved')], default=None, max_length=20),
        ),
    ]
