# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0028_one_to_one_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='global_sequence',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
