# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-11 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0029_question_global_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='change_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='revision',
            name='is_contribution',
            field=models.BooleanField(default=False),
        ),
    ]
