# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 17:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0017_add_reference_field'),
        ('exams', '0030_add_fields_to_revision'),
    ]

    operations = [
    ]
