# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 21:50
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0030_add_fields_to_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='credits',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
        ),
        migrations.AddField(
            model_name='session',
            name='submission_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
