# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0031_merge_20170822_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examtype',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='exam_types',
            field=models.ManyToManyField(to='exams.ExamType'),
        ),
    ]
