# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 23:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0031_merge_20170822_2057'),
        ('exams', '0031_add_credits_to_exams'),
    ]

    operations = [
    ]
