# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0032_m2m_exam_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_types',
            field=models.ManyToManyField(to='exams.ExamType'),
        ),
    ]
