# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 21:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0034_fill_exam_exam_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='exam_types',
        ),
    ]
