# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 06:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0035_remove_category_exam_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.Exam'),
        ),
    ]
