# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0038_required_question_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_types',
            field=models.ManyToManyField(blank=True, to='exams.ExamType'),
        ),
        migrations.AlterField(
            model_name='question',
            name='exam_types',
            field=models.ManyToManyField(blank=True, to='exams.ExamType'),
        ),
        migrations.AlterField(
            model_name='session',
            name='exam_types',
            field=models.ManyToManyField(blank=True, to='exams.ExamType'),
        ),
    ]
