# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0039_optional_exam_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='explanation_figure',
            field=models.ImageField(blank=True, upload_to='explanation_images'),
        ),
    ]
