# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 06:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0032_merge_20170824_0218'),
        ('exams', '0040_revision_explanation_figure'),
    ]

    operations = [
    ]
