# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 19:48
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0042_add_approved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='credits',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=''),
        ),
    ]
