# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0044_choice_text_255_length'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Status',
            new_name='Issue',
        ),
        migrations.RemoveField(
            model_name='revision',
            name='statuses',
        ),
        migrations.AddField(
            model_name='issue',
            name='is_blocker',
            field=models.BooleanField(default=False),
        ),
        migrations.RenameField(
            model_name='question',
            old_name='statuses',
            new_name='issues',
        ),
        migrations.AlterField(
            model_name='question',
            name='issues',
            field=models.ManyToManyField(blank=True, to='exams.Issue'),
        ),
    ]
