# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 12:41
from __future__ import unicode_literals

from django.db import migrations


def remove_complete(apps, schema_editor):
    Issue = apps.get_model('exams', 'Issue')
    try:
        complete_issue = Issue.objects.get(code_name="COMPLETE")
    except Issue.DoesNotExist:
        pass
    else:
        complete_issue.delete()

def add_complete(apps, schema_editor):
    Issue = apps.get_model('exams', 'Issue')
    Question = apps.get_model('exams', 'Question')
    complete_issue = Issue.objects.create(code_name="COMPLETE",
                                          name="Complete and valid")

    for question in Question.objects.filter(issues__isnull=True):
        question.issues.add(complete_issue)

class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0045_rename_statuses_to_issues'),
    ]

    operations = [
        migrations.RunPython(remove_complete,
                             reverse_code=add_complete)
    ]
