# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 12:41
from __future__ import unicode_literals

from django.db import migrations

def add_incomprehensible(apps, schema_editor):
    Issue = apps.get_model('exams', 'Issue')
    incomprehensible_issue = Issue.objects.create(code_name="INCOMPREHENSIBLE",
                                                  name="Incomprehensible question",
                                                  is_blocker=True)

def remove_incomprehensible(apps, schema_editor):
    Issue = apps.get_model('exams', 'Issue')
    Issue.objects.get(code_name="INCOMPREHENSIBLE").delete()

class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0046_remove_complete_status'),
    ]

    operations = [
        migrations.RunPython(add_incomprehensible,
                             reverse_code=remove_incomprehensible)
    ]
