# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0047_add_incomprehensible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='question_filter',
            field=models.CharField(choices=[('ALL', 'All complete'), ('UNUSED', 'Unused'), ('INCORRECT', 'Incorrect'), ('MARKED', 'Marked'), ('INCOMPLETE', 'Incomplete')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_mode',
            field=models.CharField(choices=[('EXPLAINED', 'Explained'), ('UNEXPLAINED', 'Unexplained'), ('SOLVED', 'Solved'), ('INCOMPLETE', 'Incomplete')], default=None, max_length=20),
        ),
    ]
