# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 22:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0048_incomplete_question_sessions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerCorrection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justification', models.TextField(default='')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('choice', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_correction', to='exams.Choice')),
                ('opposing_users', models.ManyToManyField(blank=True, related_name='opposed_corrections', to=settings.AUTH_USER_MODEL)),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('supporting_users', models.ManyToManyField(blank=True, related_name='supported_corrections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='submission_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
