# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0049_answer_correction'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
