# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-20 12:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0051_highlight'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExplanationRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('reference', models.TextField(default='', blank=True)),
                ('figure', models.ImageField(blank=True, upload_to='explanation_images')),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_first', models.BooleanField(default=False)),
                ('is_last', models.BooleanField(default=False)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explanation_revisions', to='exams.Question')),
                ('submitter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_explanations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
