# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-22 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0054_rename_explanation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='latest_explanation_revision',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='latest_explanation_of', to='exams.ExplanationRevision'),
        ),
        migrations.AddField(
            model_name='question',
            name='best_latest_revision',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='best_latest_revision_of', to='exams.Revision'),
        ),
    ]
