# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-13 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0055_examdate'),
        ('exams', '0055_add_mnemonics'),
    ]

    operations = [
    ]
