# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-22 12:12
from __future__ import unicode_literals

from django.db import migrations

def add_latest_revisions(apps, schema_editor):
    Question = apps.get_model('exams', 'Question')

    for question in Question.objects.iterator():
        question.latest_explanation_revision = question.explanation_revisions\
                                                       .filter(is_deleted=False)\
                                                       .order_by('submission_date')\
                                                       .last()
        latest_approved_revision = question.revision_set.filter(is_approved=True,
                                                                is_deleted=False)\
                                                        .order_by('submission_date')\
                                                        .last()
        latest_revision_by_editor = question.revision_set.filter(is_deleted=False,
                                                                 is_contribution=False)\
                                                         .order_by('submission_date')\
                                                         .last()
        latest_revision = question.revision_set\
                                  .filter(is_deleted=False)\
                                  .order_by('submission_date')\
                                  .last()
        question.best_latest_revision = latest_approved_revision or \
                                        latest_revision_by_editor or \
                                        latest_revision
        question.save()

def empty_latest_revisions(apps, schema_editor):
    Question = apps.get_model('exams', 'Question')
    Question.objects.update(best_latest_revision=None,
                            latest_explanation_revision=None)


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0055_add_latest_revision_relationships'),
    ]

    operations = [
        migrations.RunPython(add_latest_revisions,
                             reverse_code=empty_latest_revisions)
    ]
