# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-16 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0056_merge_20171213_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='explanationrevision',
            name='is_contribution',
            field=models.BooleanField(default=False),
        ),
    ]
