# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-18 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0058_fill_explanation_is_contribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='has_finished',
            field=models.NullBooleanField(default=None),
        ),
    ]
