# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 20:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0062_skipped_and_automatic_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='assigned_editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
