# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0063_question_assigned_editor'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='best_revision',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='best_of', to='exams.Revision'),
        ),
    ]
