# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 10:12
from __future__ import unicode_literals

from django.db import migrations


def fill_best_revision(apps, schema_editor):
    Question = apps.get_model('exams', 'Question')

    for question in Question.objects.filter(is_deleted=False):
        best_revision = question.revision_set.filter(is_approved=True,
                                                     is_deleted=False)\
                                             .order_by('submission_date')\
                                             .last() or \
                        question.revision_set.filter(is_deleted=False,
                                                     is_contribution=False)\
                                             .order_by('submission_date')\
                                             .last() or \
                        question.revision_set.filter(is_deleted=False)\
                                             .order_by('submission_date')\
                                             .last()

        question.best_revision = best_revision
        question.save()

def empty_best_revision(apps, schema_editor):
    Question = apps.get_model('exams', 'Question')
    Question.objects.update(best_revision=None)

class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0064_question_best_revision'),
    ]

    operations = [
        migrations.RunPython(fill_best_revision,
                             reverse_code=empty_best_revision)
    ]
