# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 21:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0065_fill_best_revision'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duplicate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio', models.FloatField()),
                ('revision_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('KEPT_FIRST', 'Kept first'), ('KEPT_SECOND', 'Kept second'), ('DECLINED', 'Declined')], default='PENDING', max_length=20)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('first_revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_duplicates', to='exams.Revision')),
                ('reviser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('second_revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_duplicates', to='exams.Revision')),
            ],
        ),
    ]
