# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-03 13:54
from __future__ import unicode_literals

from django.db import migrations


def create_duplicate_container(apps, schema_editor):
    DuplicateContainer = apps.get_model('exams', 'DuplicateContainer')
    Duplicate = apps.get_model('exams', 'Duplicate')

    for duplicate in Duplicate.objects.select_related('first_revision',
                                                      'first_revision__question',
                                                      'second_revision',
                                                      'second_revision__question').all():
        # The primary question is always the one with lower primary
        # key.  The secondary question is always the one with higher
        # primary key.
        lower_question_pk = min([duplicate.first_revision.question.pk,
                                 duplicate.second_revision.question.pk])

        if duplicate.first_revision.question.pk == lower_question_pk:
            primary_question = duplicate.first_revision.question
            secondary_question = duplicate.second_revision.question
        else:
            primary_question = duplicate.second_revision.question
            secondary_question = duplicate.first_revision.question

        container = DuplicateContainer.objects.create(
            primary_question=primary_question,
            status=duplicate.status,
            reviser=duplicate.reviser,
            revision_date=duplicate.revision_date)
        duplicate.container = container
        duplicate.question = secondary_question
        duplicate.save()

def delete_duplicate_container(apps, schema_editor):
    DuplicateContainer = apps.get_model('exams', 'DuplicateContainer')
    Duplicate = apps.get_model('exams', 'Duplicate')

    Duplicate.objects.update(container=None, question=None)
    DuplicateContainer.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0067_duplicate_container'),
    ]

    operations = [
        migrations.RunPython(create_duplicate_container,
                             reverse_code=delete_duplicate_container)
    ]
