# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-03 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0068_create_duplicate_container'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duplicate',
            name='first_revision',
        ),
        migrations.RemoveField(
            model_name='duplicate',
            name='reviser',
        ),
        migrations.RemoveField(
            model_name='duplicate',
            name='revision_date',
        ),
        migrations.RemoveField(
            model_name='duplicate',
            name='second_revision',
        ),
        migrations.RemoveField(
            model_name='duplicate',
            name='status',
        ),
        migrations.RemoveField(
            model_name='duplicate',
            name='submission_date',
        ),
    ]
