# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 19:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0069_clean_up_duplicate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=40)),
                ('scope', models.CharField(choices=[('ALL', 'Both revisions and changes'), ('REVISIONS', 'Revisions'), ('CHOICES', 'Choices')], default='ALL', max_length=15)),
                ('regex_pattern', models.CharField(max_length=120)),
                ('regex_replacement', models.CharField(max_length=120, blank=True)),
                ('is_automatic', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SuggestedChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('KEPT', 'Kept'), ('DECLINED', 'Declined')], default='PENDING', max_length=20)),
                ('revision_date', models.DateTimeField(blank=True, null=True)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('reviser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Revision')),
                ('rules', models.ManyToManyField(blank=True, to='exams.Rule')),
            ],
        ),
    ]
