# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0070_suggested_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
