# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-10 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0071_rule_is_disabled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rule',
            options={'ordering': ('priority',)},
        ),
        migrations.AddField(
            model_name='rule',
            name='priority',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
