# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-10 15:23
from __future__ import unicode_literals

from django.db import migrations
from django.db import connection

def remove_non_unique(apps, schema_editor):
    Answer = apps.get_model('exams', 'Answer')

    with connection.cursor() as cursor:
        cursor.execute("SELECT session_id, question_id FROM exams_answer GROUP BY session_id, question_id HAVING COUNT(*) > 1;")
        results = cursor.fetchall()
    for session_id, question_id in results:
        non_unique_answers = Answer.objects.filter(session_id=session_id,
                                                   question_id=question_id)
        answer_to_keep = non_unique_answers.filter(choice__isnull=False).last() or \
                         non_unique_answers.first()
        answers_to_delete = non_unique_answers.exclude(pk=answer_to_keep.pk)
        print("Deleting {} duplicate answers of session #{} and question #{}".format(answers_to_delete.count(), session_id, question_id))
        answers_to_delete.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0072_rule_priority'),
    ]

    operations = [
        migrations.RunPython(remove_non_unique),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set([('session', 'question')]),
        ),
    ]
