# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-10 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0073_unique_answer_per_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.Question'),
        ),
    ]
