# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-10 19:31
from __future__ import unicode_literals

from django.db import migrations

def fill_question(apps, schema_editor):
    Highlight = apps.get_model('exams', 'Highlight')

    for highlight in Highlight.objects.select_related('revision',
                                                      'revision__question')\
                                      .all():
        highlight.question = highlight.revision.question
        highlight.save()

def empty_question(apps, schema_editor):
    Highlight = apps.get_model('exams', 'Highlight')
    Highlight.objects.update(question=None)

class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0074_highlight_question'),
    ]

    operations = [
        migrations.RunPython(fill_question,
                             reverse_code=empty_question)
    ]
