# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-10 19:28
from __future__ import unicode_literals

from django.db import migrations
from django.db import connection

def remove_non_unique(apps, schema_editor):
    Highlight = apps.get_model('exams', 'Highlight')

    with connection.cursor() as cursor:
        cursor.execute("SELECT session_id, question_id FROM exams_highlight GROUP BY session_id, question_id HAVING COUNT(*) > 1;")
        results = cursor.fetchall()
    for session_id, question_id in results:
        non_unique_highlights = Highlight.objects.filter(session_id=session_id,
                                                         question_id=question_id)\
                                                 .order_by('-revision')
        highlight_to_keep = non_unique_highlights.first()
        highlights_to_delete = non_unique_highlights.exclude(pk=highlight_to_keep.pk)
        print("Deleting {} duplicate highlights of session #{} and question #{}".format(highlights_to_delete.count(), session_id, question_id))
        highlights_to_delete.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0075_fill_highlight_question'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[migrations.RunPython(remove_non_unique)],
            state_operations=[migrations.AlterUniqueTogether(
                                        name='highlight',
                                        unique_together=set([('session', 'question')]))]
            )
    ]
