# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-16 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0078_fill_question_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duplicatecontainer',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('KEPT', 'Kept'), ('EDITED', 'Edited'), ('DECLINED', 'Declined')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='suggestedchange',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('KEPT', 'Kept'), ('EDITED', 'Edited'), ('DECLINED', 'Declined')], default='PENDING', max_length=20),
        ),
    ]
