# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-24 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0081_validate_rule_regex'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('primary_background_color', models.CharField(blank=True, max_length=50)),
                ('secondary_background_color', models.CharField(blank=True, max_length=50)),
                ('tertiary_background_color', models.CharField(blank=True, max_length=50)),
                ('primary_font_color', models.CharField(blank=True, max_length=50)),
                ('secondary_font_color', models.CharField(blank=True, max_length=50)),
                ('tertiary_font_color', models.CharField(blank=True, max_length=50)),
                ('highlight_background', models.CharField(blank=True, max_length=50)),
                ('highlight_color', models.CharField(blank=True, max_length=50)),
                ('table_active', models.CharField(blank=True, max_length=50)),
                ('table_hover', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
