# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-30 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0083_add_default_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='parent_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='exams.Session'),
        ),
        migrations.AddField(
            model_name='session',
            name='secret_key',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
