# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-30 15:38
from __future__ import unicode_literals
import random
import string

from django.db import migrations

def fill_secret_key(apps, schema_editor):
    Session = apps.get_model('exams', 'Session')

    chars = string.ascii_lowercase + string.digits
    
    for session in Session.objects.order_by('pk'):
        print("Filling #{}...".format(session.pk))
        secret_key = "".join([random.choice(chars) for i in range(10)])
        session.secret_key = secret_key
        session.save()

def empty_secret_key(apps, schema_editor):
    Session = apps.get_model('exams', 'Session')
    Session.objects.update(secret_key="")

class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0084_shared_sessions'),
    ]

    operations = [
        migrations.RunPython(fill_secret_key,
                             reverse_code=empty_secret_key)
    ]
