# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-01 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0085_fill_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiontheme',
            name='tooltip_background_color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sessiontheme',
            name='tooltip_font_color',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
