# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-24 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0086_customize_tooltips'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='is_public',
            new_name='was_announced',
        ),
        migrations.AddField(
            model_name='category',
            name='is_listed',
            field=models.BooleanField(default=True, verbose_name='This category is listed upon showing categories and on the sidebar'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='was_announced',
            field=models.BooleanField(default=True, verbose_name='This exam was announced and is readily available for users who are not editors'),
        ),
    ]
