# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-23 13:38
from __future__ import unicode_literals

from django.db import migrations

def fill_latest_explanation(apps, schema_editor):
    Question = apps.get_model('exams', 'Question')

    for question in Question.objects.filter(explanation_revisions__is_deleted=False)\
                                    .prefetch_related('explanation_revisions')\
                                    .distinct()\
                                    .iterator():
        question.latest_explanation_revision = question.explanation_revisions.filter(is_deleted=False)\
                                                                              .order_by('submission_date')\
                                                                              .last()
        question.save()

def empty_latest_explanation(apps, schema_editor):
    Question = apps.get_model('exams', 'Question')
    Question.objects.update(latest_explanation_revision=None)

class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0088_question_latest_explanation_revision'),
    ]

    operations = [
        migrations.RunPython(fill_latest_explanation,
                             reverse_code=empty_latest_explanation)
    ]
