# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-24 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0089_fill_latest_explanation_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_user_count',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='count_update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='incorrect_user_count',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='skipping_user_count',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='total_user_count',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
