# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-25 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0090_user_answer_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='correct_answer_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='session',
            name='incorrect_answer_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='session',
            name='skipped_answer_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
