# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-25 07:23
from __future__ import unicode_literals

from django.db import migrations

def fill_session_answer_counts(apps, schema_editor):
    Session = apps.get_model('exams', 'Session')
    Question = apps.get_model('exams', 'Question')

    for session in Session.objects.exclude(session_mode__in=['SOLVED',
                                                             'INCOMPLETE']):
        correct_count = session.questions.filter(answer__choice__is_right=True,
                                                 answer__session=session)\
                                         .count() or 0
        incorrect_count = session.questions.filter(answer__choice__is_right=False,
                                                 answer__session=session)\
                                         .count() or 0
        skipped_count = session.questions.filter(answer__choice__isnull=True,
                                                 answer__session=session)\
                                         .count() or 0

        session.correct_answer_count = correct_count
        session.incorrect_answer_count = incorrect_count
        session.skipped_answer_count = skipped_count

        session.save()

def empty_session_answer_counts(apps, schema_editor):
    Session = apps.get_model('exams', 'Session')
    Session.objects.update(correct_answer_count=0,
                           incorrect_answer_count=0,
                           skipped_answer_count=0)

class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0091_session_answer_counts'),
    ]

    operations = [
        migrations.RunPython(fill_session_answer_counts,
                             reverse_code=empty_session_answer_counts)
    ]
