# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-25 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0092_fill_session_answer_counts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='has_finished',
        ),
        migrations.AddField(
            model_name='session',
            name='unused_question_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
