# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-13 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0094_fill_session_unused_question_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='college_limit',
            new_name='group_limit',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='batches_allowed_to_take',
            new_name='levels_allowed_to_take',
        ),
        migrations.RenameField(
            model_name='examdate',
            old_name='batch',
            new_name='level',
        ),
    ]
