# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-14 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_optional_group_instituion'),
        ('exams', '0096_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='groups_allowed_to_take',
        ),
        migrations.AddField(
            model_name='exam',
            name='groups_allowed_to_take',
            field=models.ManyToManyField(blank=True, to='accounts.Group'),
        ),
        migrations.RemoveField(
            model_name='exam',
            name='levels_allowed_to_take',
        ),
        migrations.AddField(
            model_name='exam',
            name='levels_allowed_to_take',
            field=models.ManyToManyField(blank=True, to='accounts.Level'),
        ),
    ]
