# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-01 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0098_exam_inherits_sources'),
    ]

    operations = [
        migrations.CreateModel(
            name='Figure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('figure', models.ImageField(upload_to='figures')),
                ('caption', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='explanationrevision',
            name='figures',
            field=models.ManyToManyField(blank=True, to='exams.Figure'),
        ),
        migrations.AddField(
            model_name='revision',
            name='figures',
            field=models.ManyToManyField(blank=True, to='exams.Figure'),
        ),
    ]
