# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-27 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0100_create_figures'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.Question'),
        ),
        migrations.AddField(
            model_name='revision',
            name='choices',
            field=models.ManyToManyField(blank=True, related_name='revision_set', to='exams.Choice'),
        ),
    ]
