# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-20 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0104_session_share_results'),
    ]

    operations = [
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('tooltip', models.TextField()),
                ('upper_limit', models.PositiveIntegerField(null=True)),
                ('lower_limit', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='question',
            old_name='correct_user_count',
            new_name='correct_first_timer_count',
        ),
        migrations.RemoveField(
            model_name='question',
            name='count_update_date',
        ),
        migrations.RemoveField(
            model_name='question',
            name='incorrect_user_count',
        ),
        migrations.RemoveField(
            model_name='question',
            name='skipping_user_count',
        ),
        migrations.AddField(
            model_name='answer',
            name='is_first',
            field=models.BooleanField(default=False, verbose_name='Is this the first time this question was answered by the user?'),
        ),
        migrations.AddField(
            model_name='exam',
            name='last_answer_for_difficulty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.Answer'),
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.Difficulty'),
        ),
        migrations.AddField(
            model_name='session',
            name='difficulties',
            field=models.ManyToManyField(blank=True, to='exams.Difficulty'),
        ),
    ]
