# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-20 18:52
from __future__ import unicode_literals

from django.db import migrations

def forward(apps, schema_editor):
    Difficulty = apps.get_model('exams', 'Difficulty')

    Difficulty.objects.create(label="Easy: Questions you should not miss",
                              tooltip='These are the questions answered correctly by 75% or more of examinees in the first time.',
                              upper_limit=100,
                              lower_limit=76)
    Difficulty.objects.create(label='Doable: Questions you can manage',
                              tooltip='These are the questions answered correctly by 51-75% of examinees in the first time.',
                              upper_limit=75,
                              lower_limit=51)
    Difficulty.objects.create(label='Tricky: Questions to pay attention to',
                              tooltip='These are the questions answered correctly by 26-50% of examinees in the first time.',
                              upper_limit=50,
                              lower_limit=26)
    Difficulty.objects.create(label='Challenging: Questions that can get you in trouble',
                              tooltip='These are the questions answered correctly only by 25% or less of examinees in the first time.',
                              upper_limit=25,
                              lower_limit=0)

def backward(apps, schema_editor):
    Difficulty = apps.get_model('exams', 'Difficulty')
    Difficulty.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0105_difficulty'),
    ]

    operations = [
        migrations.RunSQL("UPDATE exams_answer SET is_first=TRUE WHERE id IN (SELECT MIN(exams_answer.id) FROM exams_answer INNER JOIN exams_session ON exams_answer.session_id=exams_session.id WHERE choice_id IS NOT NULL GROUP BY exams_session.submitter_id, question_id);", "UPDATE exams_answer SET is_first=FALSE;"),
        migrations.RunPython(forward, backward)
    ]
