# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-23 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0107_update_difficulty_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_mode',
            field=models.CharField(choices=[('EXPLAINED', 'Explained'), ('UNEXPLAINED', 'Unexplained'), ('SOLVED', 'Solved'), ('INCOMPLETE', 'Incomplete')], default='EXPLAINED', max_length=20),
        ),
    ]
