# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-23 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0108_default_session_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duplicate',
            name='container',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.DuplicateContainer'),
        ),
    ]
