# Generated by Django 2.2.5 on 2019-10-24 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0109_fill_on_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='examinee_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_first',
            field=models.BooleanField(blank=True, default=False, verbose_name='Is this the first time this question was answered by the user?'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_listed',
            field=models.BooleanField(blank=True, default=True, verbose_name='This category is listed upon showing categories and on the sidebar'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='was_announced',
            field=models.BooleanField(blank=True, default=True, verbose_name='This exam was announced and is readily available for users who are not editors'),
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100)),
                ('number_of_questions', models.PositiveIntegerField(blank=True, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Exam')),
            ],
        ),
    ]
