# Generated by Django 2.2.5 on 2019-10-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0110_support_examiners'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
