# Generated by Django 2.2.5 on 2019-10-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0111_session_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='session_mode',
            field=models.CharField(choices=[('EXPLAINED', 'Explained'), ('UNEXPLAINED', 'Unexplained'), ('SOLVED', 'Solved'), ('INCOMPLETE', 'Incomplete')], default='UNEXPLAINED', max_length=20),
        ),
    ]
